export default function Head() {
  return (
    <>
      <title>MimoLaundry</title>
      <meta name="description" content="Generated by Cappa Database" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}